-- Auto-generated from schema-map-postgres.yaml (map@sha1:F0EE237771FBA8DD7C4E886FF276F91A862C3718)
-- engine: postgres
-- table:  rate_limits

CREATE TABLE IF NOT EXISTS rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_type TEXT NOT NULL,                   -- 'ip','user','api_key','tenant'
  subject_id   VARCHAR(128) NOT NULL,
  name         VARCHAR(120) NOT NULL,          -- e.g. 'login','api'
  window_size_sec INTEGER NOT NULL,
  limit_count    INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_rate_limits UNIQUE (subject_type, subject_id, name, window_size_sec),
  CONSTRAINT chk_rate_window CHECK (window_size_sec > 0),
  CONSTRAINT chk_rate_limit  CHECK (limit_count  > 0)
);
